x-common-variables: &common-variables
  GRAPE_APH: "30001"
  GRAPE_HOST: "grape1"

services:
  grape1:
    container_name: grape1
    build:
      context: .
      dockerfile: Dockerfile.grape
    restart: unless-stopped
    networks:
      - grapes
    environment:
      <<: *common-variables
      GRAPE_DP: "20001"
      GRAPE_BN: "20002"
      GRAPE_BIND: "grape2"

  grape2:
    container_name: grape2
    build:
      context: .
      dockerfile: Dockerfile.grape
    restart: unless-stopped
    depends_on:
      grape1:
        condition: service_healthy
    networks:
      - grapes
    environment:
      <<: *common-variables
      GRAPE_DP: "20002"
      GRAPE_APH: "40001"
      GRAPE_BN: "20001"
      GRAPE_BIND: "grape1"

  exchange_server1:
    build: .
    command: node server/index.js
    environment:
      <<: *common-variables
      STORAGE_FILE: "orderbook1.json"
    depends_on:
      grape1:
        condition: service_healthy
      grape2:
        condition: service_healthy
    networks:
      - grapes

  exchange_server2:
    build: .
    command: node server/index.js
    environment:
      <<: *common-variables
      STORAGE_FILE: "orderbook2.json"
    depends_on:
      grape1:
        condition: service_healthy
      grape2:
        condition: service_healthy
    networks:
      - grapes

  exchange_client:
    build: .
    command: node client/index.js
    environment:
      <<: *common-variables
      STORAGE_FILE: "orderbook1.json"
    depends_on:
      - grape1
      - grape2
      - exchange_server1
      - exchange_server2
    networks:
      - grapes

networks:
  grapes:
    driver: bridge
